apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-backend.fullname" . }}-db-secret
  labels:
    {{- include "helm-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_NAME: {{ .Values.database.name | quote }}